#!/usr/bin/env bash
# displays the visitor IP along with the HTTP status code from the Apache log file
cat apache-access.log | awk '{print $1}' | sort | uniq -c | sort -nr | awk '{printf "%-8s ==> %s\n", $2, $1}' 
