#!/usr/bin/env bash
#displays bad luck for the 4th loop iteration
#displays good luck for the 8th loop iteration
#displays Best School for the other iterations
var=1
while [ $var -le 10 ]
do
        (( var++ ))
        if [ $var -eq 5 ]
        then
                echo "bad luck"
	elif [ $var -eq 9 ]
	then
		echo "good luck"
	else
		echo "Best School"
        fi
done
