#!/usr/bin/env bash
#Bash script that configures an Ubuntu server
cp /etc/hosts ~/hosts.new
file=~/hosts.new
sed -i 's/127.0.0.1/127.0.0.2/g' $file
echo "8.8.8.8		facebook.com">>$file
cp -f ~/hosts.new /etc/hosts
